version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: bank_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bank_application
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - bank-network

  redis:
    image: redis:7.0
    container_name: bank_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - bank-network

  bankapp:
    build: .
    container_name: bank_app
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://bank_mysql:3306/bank_application?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      JWT_SECRET: U3Nh4sJt6+vGJx0XoRLtdmFY/NTK8omIGArWoUcfK8U=
      CLOUDINARY_CLOUD_NAME: dm4dc4nbi
      CLOUDINARY_API_KEY: 746957422131865
      CLOUDINARY_API_SECRET: P1Shpim6BwUtinLKDndtKFUZ8Sg
      SPRING_MAIL_HOST: smtp.mailtrap.io
      SPRING_MAIL_PORT: 2525
      SPRING_MAIL_USERNAME: dd228f7d1b78e5
      SPRING_MAIL_PASSWORD: 4e6ab3a560200b
    ports:
      - "8080:8080"
    networks:
      - bank-network
    command: ["./wait-for-it.sh", "bank_mysql:3306", "--timeout=120", "--strict", "--", "java", "-jar", "app.jar"]

volumes:
  db_data:

networks:
  bank-network:
