spring:
  datasource:
    url: jdbc:mysql://bank_mysql:3306/${MYSQL_DATABASE}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8&useUnicode=true
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 20000
      pool-name: HikariCP

  jpa:
    hibernate:
      ddl-auto: none  # Disable Hibernate auto schema updates
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: false

  redis:
    host: ${SPRING_DATA_REDIS_HOST}
    port: ${SPRING_DATA_REDIS_PORT}
    lettuce:
      shutdown-timeout: 100ms
      pool:
        max-active: 10
        max-idle: 5
        min-idle: 1
      validate-connection: true
    timeout: 5000ms
    reconnect-on-failure: true

  cache:
    type: redis
    redis:
      time-to-live: 600000 # 10 minutes
      cache-null-values: false
      use-key-prefix: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-on-validation-error: true
    clean-disabled: false  # allow Flyway to clean when needed
    locations: classpath:db/migration
    connect-retries: 5

logging:
  level:
    root: INFO
    org.flywaydb: DEBUG
    com.bankapplication: DEBUG
    org.springframework: INFO

server:
  error:
    include-stacktrace: ALWAYS
    include-message: ALWAYS


transaction:
  deposit-limit: 10000000
  withdral_limt: 5000000
  rapidTransactionThreshold:5: 5


