spring:
  datasource:
    url: jdbc:mysql://bank_mysql:3306/bank_application?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 20000
      pool-name: HikariCP

  jpa:
    hibernate:
      ddl-auto: none  # Disable Hibernate auto schema updates
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: false

  redis:
    host: redis
    port: 6379

  cache:
    type: redis
    redis:
      time-to-live: 600000 # 10 minutes

  flyway:
    enabled: true
    baseline-on-migrate: true
    clean-on-validation-error: true
    clean-disabled: false  # allow Flyway to clean when needed
    locations: classpath:db/migration
    connect-retries: 5

logging:
  level:
    root: INFO
    org.flywaydb: DEBUG
    com.bankapplication: DEBUG
    org.springframework: INFO

server:
  error:
    include-stacktrace: ALWAYS
    include-message: ALWAYS
